# Generated by Django 3.2.5 on 2021-08-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Harry', max_length=16),
            preserve_default=False,
        ),
    ]
