# Generated by Django 3.2.5 on 2021-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('completed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='todo',
            field=models.ManyToManyField(to='main_app.Todo'),
        ),
    ]
