# Generated by Django 3.2.6 on 2021-08-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210818_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='spider', max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='exp_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='exp_next',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='health_current',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='health_max',
            field=models.IntegerField(default=50),
        ),
    ]
